version: '3.1'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: always
    ports:
      - "8787:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /result:/result
    networks:
      - marketduck_app-network
    dns:
      - 8.8.8.8

volumes:
  jenkins_home:

networks:
  marketduck_app-network:
    external: true