# redis-server.yml
version: '3.7'
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    ports:
      - 16379:6379
